### ISSUE TITLE
writeStatic Error

### ISSUE THREAD

**Issue by uhteddy** [TorstenDittmann/svelte-adapter-static-digitalocean#1]
When using the current version of `svelte-adapter-static-digitalocean` you will receive an error for "writeStatic has been removed. Please ensure you are using the latest version of svelte-adapter-static-digitalocean"

This error happens as the @sveltejs/adapter-static version is outdated.

 @sveltejs/adapter-static needs to be updated from version 1.0.0-next.34 > 1.0.0-next.38

**Comment by uhteddy** [comment]
Created a PR #2

**Comment by TorstenDittmann** [comment]
Upgraded to latest 1.0.0 🙏🏻 

Sorry, didn't see that there was an open issue or PR.
